apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "helium.fullname" . }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ include "helium.fullname" . }}-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        port:
          number: {{ .Values.service.port }}
        host: {{ include "helium.fullname" . }}
