name: Load Test

on:
  push:
    paths:
    - '.github/workflows/perfTest.yml'

  schedule:
    # Run daily at 3:00 AM
    - cron: "0 3 * * *"

jobs:

  load-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install WebV
      run: |
        dotnet tool install -g webvalidate

    - name: run baseline test
      run: |
        cd TestFiles
        webv -s bluebell gelato sherbert -f baseline.json

    - name: run validation test
      run: |
        # run web validation test
        # 10 req/sec for 5 minutes
        cd TestFiles
        webv -s bluebell gelato sherbert -f benchmark.json -r -l 100 --duration 300
